import urllib2

urls = ['http://www.artsandscience.utoronto.ca/ofr/timetable/winter/asabs.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/csus.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/ana.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/ant.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/far.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/ast.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/bch.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/asdn.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/cita.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/csb.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/chm.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/cine.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/clas.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/col.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/ctep.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/asi.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/crim.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/dts.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/drama.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/es.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/eas.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/eeb.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/eco.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/ire.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/eng.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/envmt.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/ethic.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/ceres.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/assem.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/for.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/fre.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/ggr.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/ger.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/his.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/ihpst.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/hmb.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/imm.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/otc.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/innis.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/ita.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/jsp.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/lmp.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/las.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/lin.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/mat.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/medgm.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/music.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/nmc.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/new.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/nusci.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/online.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/glaf.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/phm.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/pcl.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/phl.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/phy.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/pol.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/psl.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/psy.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/spp.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/rlg.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/compg.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/sdst.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/sla.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/soc.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/sas.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/spa.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/smc.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/stat.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/trin.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/uc.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/vic.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/wdw.html',
 'http://www.artsandscience.utoronto.ca/ofr/timetable/winter/wgsi.html']

for url in urls:
  html = urllib2.urlopen(url).read()
  path = 'courses_2014/' + url.split('timetable/winter/')[1]
  with open(path, "wb") as code:
    code.write(html)
